// Generated by gencpp from file modrob_simulation/RobotGroupModuleOrder.msg
// DO NOT EDIT!


#ifndef MODROB_SIMULATION_MESSAGE_ROBOTGROUPMODULEORDER_H
#define MODROB_SIMULATION_MESSAGE_ROBOTGROUPMODULEORDER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <modrob_simulation/RobotModuleOrder.h>

namespace modrob_simulation
{
template <class ContainerAllocator>
struct RobotGroupModuleOrder_
{
  typedef RobotGroupModuleOrder_<ContainerAllocator> Type;

  RobotGroupModuleOrder_()
    : robots()  {
    }
  RobotGroupModuleOrder_(const ContainerAllocator& _alloc)
    : robots(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::modrob_simulation::RobotModuleOrder_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::modrob_simulation::RobotModuleOrder_<ContainerAllocator> >::other >  _robots_type;
  _robots_type robots;





  typedef boost::shared_ptr< ::modrob_simulation::RobotGroupModuleOrder_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::modrob_simulation::RobotGroupModuleOrder_<ContainerAllocator> const> ConstPtr;

}; // struct RobotGroupModuleOrder_

typedef ::modrob_simulation::RobotGroupModuleOrder_<std::allocator<void> > RobotGroupModuleOrder;

typedef boost::shared_ptr< ::modrob_simulation::RobotGroupModuleOrder > RobotGroupModuleOrderPtr;
typedef boost::shared_ptr< ::modrob_simulation::RobotGroupModuleOrder const> RobotGroupModuleOrderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::modrob_simulation::RobotGroupModuleOrder_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::modrob_simulation::RobotGroupModuleOrder_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::modrob_simulation::RobotGroupModuleOrder_<ContainerAllocator1> & lhs, const ::modrob_simulation::RobotGroupModuleOrder_<ContainerAllocator2> & rhs)
{
  return lhs.robots == rhs.robots;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::modrob_simulation::RobotGroupModuleOrder_<ContainerAllocator1> & lhs, const ::modrob_simulation::RobotGroupModuleOrder_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace modrob_simulation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::modrob_simulation::RobotGroupModuleOrder_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::modrob_simulation::RobotGroupModuleOrder_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::modrob_simulation::RobotGroupModuleOrder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::modrob_simulation::RobotGroupModuleOrder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::modrob_simulation::RobotGroupModuleOrder_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::modrob_simulation::RobotGroupModuleOrder_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::modrob_simulation::RobotGroupModuleOrder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f925c4b27303a14269668a378ac29d76";
  }

  static const char* value(const ::modrob_simulation::RobotGroupModuleOrder_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf925c4b27303a142ULL;
  static const uint64_t static_value2 = 0x69668a378ac29d76ULL;
};

template<class ContainerAllocator>
struct DataType< ::modrob_simulation::RobotGroupModuleOrder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "modrob_simulation/RobotGroupModuleOrder";
  }

  static const char* value(const ::modrob_simulation::RobotGroupModuleOrder_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::modrob_simulation::RobotGroupModuleOrder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# All robots that will be built\n"
"RobotModuleOrder[] robots\n"
"================================================================================\n"
"MSG: modrob_simulation/RobotModuleOrder\n"
"# Array indices from 0 to max match joints from base joint to last joint\n"
"int8[] modules\n"
"\n"
"# Base position\n"
"geometry_msgs/Vector3 base_pos\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::modrob_simulation::RobotGroupModuleOrder_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::modrob_simulation::RobotGroupModuleOrder_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robots);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotGroupModuleOrder_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::modrob_simulation::RobotGroupModuleOrder_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::modrob_simulation::RobotGroupModuleOrder_<ContainerAllocator>& v)
  {
    s << indent << "robots[]" << std::endl;
    for (size_t i = 0; i < v.robots.size(); ++i)
    {
      s << indent << "  robots[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::modrob_simulation::RobotModuleOrder_<ContainerAllocator> >::stream(s, indent + "    ", v.robots[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MODROB_SIMULATION_MESSAGE_ROBOTGROUPMODULEORDER_H
