(cl:in-package modrob_simulation-msg)
(cl:export '(NAME-VAL
          NAME
          ORIGIN_X-VAL
          ORIGIN_X
          ORIGIN_Y-VAL
          ORIGIN_Y
          ORIGIN_Z-VAL
          ORIGIN_Z
          ORIGIN_R-VAL
          ORIGIN_R
          ORIGIN_P-VAL
          ORIGIN_P
          ORIGIN_YY-VAL
          ORIGIN_YY
          MASS-VAL
          MASS
          INTERTIA_IXX-VAL
          INTERTIA_IXX
          INTERTIA_IXY-VAL
          INTERTIA_IXY
          INTERTIA_IXZ-VAL
          INTERTIA_IXZ
          INTERTIA_IYY-VAL
          INTERTIA_IYY
          INTERTIA_IYZ-VAL
          INTERTIA_IYZ
          INTERTIA_IZZ-VAL
          INTERTIA_IZZ
          MU1-VAL
          MU1
          MU2-VAL
          MU2
          KP-VAL
          KP
          KD-VAL
          KD
          LINK_VISUAL-VAL
          LINK_VISUAL
          LINK_COLLISION-VAL
          LINK_COLLISION
))