(cl:defpackage modrob_workstation-msg
  (:use )
  (:export
   "<JOINTCONFIGCOMMANDED>"
   "JOINTCONFIGCOMMANDED"
   "<JOINTCONFIGMEASURED>"
   "JOINTCONFIGMEASURED"
   "<JOINTDESCRIPTION>"
   "JOINTDESCRIPTION"
   "<JOINTSELECTION>"
   "JOINTSELECTION"
   "<LINKCOLLISION>"
   "LINKCOLLISION"
   "<LINKDESCRIPTION>"
   "LINKDESCRIPTION"
   "<LINKVISUAL>"
   "LINKVISUAL"
   "<MODULEORDER>"
   "MODULEORDER"
   "<ROBOTCONFIGCOMMANDED>"
   "ROBOTCONFIGCOMMANDED"
   "<ROBOTCONFIGMEASURED>"
   "ROBOTCONFIGMEASURED"
   "<ROBOTDESCRIPTION>"
   "ROBOTDESCRIPTION"
   "<ROBOTSTATECOMMANDED>"
   "ROBOTSTATECOMMANDED"
  ))

