(cl:in-package modrob_workstation-msg)
(cl:export '(NAME-VAL
          NAME
          ORIGIN_X-VAL
          ORIGIN_X
          ORIGIN_Y-VAL
          ORIGIN_Y
          ORIGIN_Z-VAL
          ORIGIN_Z
          ORIGIN_R-VAL
          ORIGIN_R
          ORIGIN_P-VAL
          ORIGIN_P
          ORIGIN_YY-VAL
          ORIGIN_YY
          TYPE-VAL
          TYPE
          ARG1-VAL
          ARG1
          ARG2-VAL
          ARG2
          ARG3-VAL
          ARG3
          COLOR_NAME-VAL
          COLOR_NAME
          COLOR_R-VAL
          COLOR_R
          COLOR_G-VAL
          COLOR_G
          COLOR_B-VAL
          COLOR_B
          COLOR_A-VAL
          COLOR_A
          TEXTURE-VAL
          TEXTURE
))