(cl:in-package modrob_workstation-msg)
(cl:export '(NAME-VAL
          NAME
          TYPE-VAL
          TYPE
          ORIGIN_X-VAL
          ORIGIN_X
          ORIGIN_Y-VAL
          ORIGIN_Y
          ORIGIN_Z-VAL
          ORIGIN_Z
          ORIGIN_R-VAL
          ORIGIN_R
          ORIGIN_P-VAL
          ORIGIN_P
          ORIGIN_YY-VAL
          ORIGIN_YY
          PARENT_LINK-VAL
          PARENT_LINK
          CHILD_LINK-VAL
          CHILD_LINK
          AXIS_X-VAL
          AXIS_X
          AXIS_Y-VAL
          AXIS_Y
          AXIS_Z-VAL
          AXIS_Z
          DAMPING-VAL
          DAMPING
          FRICTION-VAL
          FRICTION
          LOWER-VAL
          LOWER
          UPPER-VAL
          UPPER
          EFFORT-VAL
          EFFORT
          VELOCITY-VAL
          VELOCITY
          SOFT_LOWER_LIMIT-VAL
          SOFT_LOWER_LIMIT
          SOFT_UPPER_LIMIT-VAL
          SOFT_UPPER_LIMIT
          K_POSITION-VAL
          K_POSITION
          K_VELOCITY-VAL
          K_VELOCITY
))