// Generated by gencpp from file modrob_control_wiimote/CartVelConfigCommanded.msg
// DO NOT EDIT!


#ifndef MODROB_CONTROL_WIIMOTE_MESSAGE_CARTVELCONFIGCOMMANDED_H
#define MODROB_CONTROL_WIIMOTE_MESSAGE_CARTVELCONFIGCOMMANDED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Twist.h>

namespace modrob_control_wiimote
{
template <class ContainerAllocator>
struct CartVelConfigCommanded_
{
  typedef CartVelConfigCommanded_<ContainerAllocator> Type;

  CartVelConfigCommanded_()
    : twist()
    , tool_activation(false)  {
    }
  CartVelConfigCommanded_(const ContainerAllocator& _alloc)
    : twist(_alloc)
    , tool_activation(false)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Twist_<ContainerAllocator>  _twist_type;
  _twist_type twist;

   typedef uint8_t _tool_activation_type;
  _tool_activation_type tool_activation;





  typedef boost::shared_ptr< ::modrob_control_wiimote::CartVelConfigCommanded_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::modrob_control_wiimote::CartVelConfigCommanded_<ContainerAllocator> const> ConstPtr;

}; // struct CartVelConfigCommanded_

typedef ::modrob_control_wiimote::CartVelConfigCommanded_<std::allocator<void> > CartVelConfigCommanded;

typedef boost::shared_ptr< ::modrob_control_wiimote::CartVelConfigCommanded > CartVelConfigCommandedPtr;
typedef boost::shared_ptr< ::modrob_control_wiimote::CartVelConfigCommanded const> CartVelConfigCommandedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::modrob_control_wiimote::CartVelConfigCommanded_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::modrob_control_wiimote::CartVelConfigCommanded_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::modrob_control_wiimote::CartVelConfigCommanded_<ContainerAllocator1> & lhs, const ::modrob_control_wiimote::CartVelConfigCommanded_<ContainerAllocator2> & rhs)
{
  return lhs.twist == rhs.twist &&
    lhs.tool_activation == rhs.tool_activation;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::modrob_control_wiimote::CartVelConfigCommanded_<ContainerAllocator1> & lhs, const ::modrob_control_wiimote::CartVelConfigCommanded_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace modrob_control_wiimote

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::modrob_control_wiimote::CartVelConfigCommanded_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::modrob_control_wiimote::CartVelConfigCommanded_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::modrob_control_wiimote::CartVelConfigCommanded_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::modrob_control_wiimote::CartVelConfigCommanded_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::modrob_control_wiimote::CartVelConfigCommanded_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::modrob_control_wiimote::CartVelConfigCommanded_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::modrob_control_wiimote::CartVelConfigCommanded_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a9a7b1d43792d9710a6cd8b7647f927f";
  }

  static const char* value(const ::modrob_control_wiimote::CartVelConfigCommanded_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa9a7b1d43792d971ULL;
  static const uint64_t static_value2 = 0x0a6cd8b7647f927fULL;
};

template<class ContainerAllocator>
struct DataType< ::modrob_control_wiimote::CartVelConfigCommanded_<ContainerAllocator> >
{
  static const char* value()
  {
    return "modrob_control_wiimote/CartVelConfigCommanded";
  }

  static const char* value(const ::modrob_control_wiimote::CartVelConfigCommanded_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::modrob_control_wiimote::CartVelConfigCommanded_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message describes workspace coordinates and tool activation\n"
"geometry_msgs/Twist twist\n"
"bool tool_activation\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::modrob_control_wiimote::CartVelConfigCommanded_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::modrob_control_wiimote::CartVelConfigCommanded_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.twist);
      stream.next(m.tool_activation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CartVelConfigCommanded_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::modrob_control_wiimote::CartVelConfigCommanded_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::modrob_control_wiimote::CartVelConfigCommanded_<ContainerAllocator>& v)
  {
    s << indent << "twist: ";
    s << std::endl;
    Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "  ", v.twist);
    s << indent << "tool_activation: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.tool_activation);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MODROB_CONTROL_WIIMOTE_MESSAGE_CARTVELCONFIGCOMMANDED_H
