// Generated by gencpp from file modrob_workstation/JointSelection.msg
// DO NOT EDIT!


#ifndef MODROB_WORKSTATION_MESSAGE_JOINTSELECTION_H
#define MODROB_WORKSTATION_MESSAGE_JOINTSELECTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace modrob_workstation
{
template <class ContainerAllocator>
struct JointSelection_
{
  typedef JointSelection_<ContainerAllocator> Type;

  JointSelection_()
    : activeJoints()  {
    }
  JointSelection_(const ContainerAllocator& _alloc)
    : activeJoints(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _activeJoints_type;
  _activeJoints_type activeJoints;





  typedef boost::shared_ptr< ::modrob_workstation::JointSelection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::modrob_workstation::JointSelection_<ContainerAllocator> const> ConstPtr;

}; // struct JointSelection_

typedef ::modrob_workstation::JointSelection_<std::allocator<void> > JointSelection;

typedef boost::shared_ptr< ::modrob_workstation::JointSelection > JointSelectionPtr;
typedef boost::shared_ptr< ::modrob_workstation::JointSelection const> JointSelectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::modrob_workstation::JointSelection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::modrob_workstation::JointSelection_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::modrob_workstation::JointSelection_<ContainerAllocator1> & lhs, const ::modrob_workstation::JointSelection_<ContainerAllocator2> & rhs)
{
  return lhs.activeJoints == rhs.activeJoints;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::modrob_workstation::JointSelection_<ContainerAllocator1> & lhs, const ::modrob_workstation::JointSelection_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace modrob_workstation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::modrob_workstation::JointSelection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::modrob_workstation::JointSelection_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::modrob_workstation::JointSelection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::modrob_workstation::JointSelection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::modrob_workstation::JointSelection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::modrob_workstation::JointSelection_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::modrob_workstation::JointSelection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "13a5be053fe753a9527bbef2b69f5491";
  }

  static const char* value(const ::modrob_workstation::JointSelection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x13a5be053fe753a9ULL;
  static const uint64_t static_value2 = 0x527bbef2b69f5491ULL;
};

template<class ContainerAllocator>
struct DataType< ::modrob_workstation::JointSelection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "modrob_workstation/JointSelection";
  }

  static const char* value(const ::modrob_workstation::JointSelection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::modrob_workstation::JointSelection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool[] activeJoints\n"
;
  }

  static const char* value(const ::modrob_workstation::JointSelection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::modrob_workstation::JointSelection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.activeJoints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointSelection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::modrob_workstation::JointSelection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::modrob_workstation::JointSelection_<ContainerAllocator>& v)
  {
    s << indent << "activeJoints[]" << std::endl;
    for (size_t i = 0; i < v.activeJoints.size(); ++i)
    {
      s << indent << "  activeJoints[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.activeJoints[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MODROB_WORKSTATION_MESSAGE_JOINTSELECTION_H
