// Generated by gencpp from file modrob_workstation/RobotConfigCommanded.msg
// DO NOT EDIT!


#ifndef MODROB_WORKSTATION_MESSAGE_ROBOTCONFIGCOMMANDED_H
#define MODROB_WORKSTATION_MESSAGE_ROBOTCONFIGCOMMANDED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <modrob_workstation/JointConfigCommanded.h>

namespace modrob_workstation
{
template <class ContainerAllocator>
struct RobotConfigCommanded_
{
  typedef RobotConfigCommanded_<ContainerAllocator> Type;

  RobotConfigCommanded_()
    : tool_activation(false)
    , joint_moves()  {
    }
  RobotConfigCommanded_(const ContainerAllocator& _alloc)
    : tool_activation(false)
    , joint_moves(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _tool_activation_type;
  _tool_activation_type tool_activation;

   typedef std::vector< ::modrob_workstation::JointConfigCommanded_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::modrob_workstation::JointConfigCommanded_<ContainerAllocator> >::other >  _joint_moves_type;
  _joint_moves_type joint_moves;





  typedef boost::shared_ptr< ::modrob_workstation::RobotConfigCommanded_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::modrob_workstation::RobotConfigCommanded_<ContainerAllocator> const> ConstPtr;

}; // struct RobotConfigCommanded_

typedef ::modrob_workstation::RobotConfigCommanded_<std::allocator<void> > RobotConfigCommanded;

typedef boost::shared_ptr< ::modrob_workstation::RobotConfigCommanded > RobotConfigCommandedPtr;
typedef boost::shared_ptr< ::modrob_workstation::RobotConfigCommanded const> RobotConfigCommandedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::modrob_workstation::RobotConfigCommanded_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::modrob_workstation::RobotConfigCommanded_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::modrob_workstation::RobotConfigCommanded_<ContainerAllocator1> & lhs, const ::modrob_workstation::RobotConfigCommanded_<ContainerAllocator2> & rhs)
{
  return lhs.tool_activation == rhs.tool_activation &&
    lhs.joint_moves == rhs.joint_moves;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::modrob_workstation::RobotConfigCommanded_<ContainerAllocator1> & lhs, const ::modrob_workstation::RobotConfigCommanded_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace modrob_workstation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::modrob_workstation::RobotConfigCommanded_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::modrob_workstation::RobotConfigCommanded_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::modrob_workstation::RobotConfigCommanded_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::modrob_workstation::RobotConfigCommanded_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::modrob_workstation::RobotConfigCommanded_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::modrob_workstation::RobotConfigCommanded_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::modrob_workstation::RobotConfigCommanded_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2bac2996406eb87049714c95e451ba2c";
  }

  static const char* value(const ::modrob_workstation::RobotConfigCommanded_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2bac2996406eb870ULL;
  static const uint64_t static_value2 = 0x49714c95e451ba2cULL;
};

template<class ContainerAllocator>
struct DataType< ::modrob_workstation::RobotConfigCommanded_<ContainerAllocator> >
{
  static const char* value()
  {
    return "modrob_workstation/RobotConfigCommanded";
  }

  static const char* value(const ::modrob_workstation::RobotConfigCommanded_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::modrob_workstation::RobotConfigCommanded_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message describes a robot arm movement\n"
"# Array indices from 0 to max match joints from base joint to last joint\n"
"bool tool_activation\n"
"JointConfigCommanded[] joint_moves\n"
"\n"
"\n"
"================================================================================\n"
"MSG: modrob_workstation/JointConfigCommanded\n"
"# This message describes a joint movement\n"
"float64 joint_angle\n"
"float64 joint_velocity\n"
"float64 joint_acceleration\n"
"float64 joint_torque\n"
;
  }

  static const char* value(const ::modrob_workstation::RobotConfigCommanded_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::modrob_workstation::RobotConfigCommanded_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tool_activation);
      stream.next(m.joint_moves);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotConfigCommanded_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::modrob_workstation::RobotConfigCommanded_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::modrob_workstation::RobotConfigCommanded_<ContainerAllocator>& v)
  {
    s << indent << "tool_activation: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.tool_activation);
    s << indent << "joint_moves[]" << std::endl;
    for (size_t i = 0; i < v.joint_moves.size(); ++i)
    {
      s << indent << "  joint_moves[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::modrob_workstation::JointConfigCommanded_<ContainerAllocator> >::stream(s, indent + "    ", v.joint_moves[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MODROB_WORKSTATION_MESSAGE_ROBOTCONFIGCOMMANDED_H
